---
abstract: 'Metadata-aware Exporter'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Exporter
requires:
  Perinci::Role::MetaAccessor: 0.26
  Perinci::Sub::Wrapper: 0.26
  Perinci::Sub::property::curry: 0
  Perinci::Util: 0.25
  Rinci: 1.1.21
  SHARYANTO::Package::Util: 0
  perl: 5.010000
resources:
  homepage: http://metacpan.org/dist/Perinci-Exporter
  repository: http://github.com/sharyanto/perl-Perinci-Exporter
version: 0.01
